### PR TITLE
First pass of class instance suggestions

### PR DESCRIPTION
**Pull request by nevadascout**
Currently this only works for variables directly set to a class instance - eg. `$inst = new MyClass();` and parameter type hints (eg. `function doSomething(MyClass $param)`

### CODE REVIEW

**Comment by TheColorRed** [comment]
I am not sure if you are aware of this, but intellisense is suggesting items that are out of scope.

autocomplete-out-of-scope

As you can see from the image `$s` is in the `ha()` function but it is getting suggested in the `he()` function.

**Comment by nevadascout** [comment]
Nice find, thanks. I'll see what I can do about this...

**Comment by nevadascout** [comment]
@TheColorRed If you get a chance, can you verify I've fixed that variable scoping issue? Thanks!

**Comment by TheColorRed** [comment]
I seem to no longer be getting suggestions, just suggestions for the variable `$s` in `ha()`

**Comment by TheColorRed** [comment]
Seems like it is still out of scope...

autocomplete-out-of-scope-2

**Comment by nevadascout** [comment]
How about now @TheColorRed ?

Your code example definitely works on my machine - did you rebuild the server before debugging the client?

**Comment by TheColorRed** [comment]
That seems to be working now, however the variable is still getting suggested (Not sure if that is as important atm).

autocomplete-out-of-scope-3

**Comment by nevadascout** [comment]
Crane isn't suggesting that variable, VS Code is.

It's on the backlog to fix (#39) but it'll require Microsoft to change something on their end.

**Comment by TheColorRed** [comment]
I noticed that when assigning a variable intellisense stops working...

```php
$db = new PDO();

// Shows suggestions
$db->

// Does not show suggestions:
$stmt = $db->
```

**Comment by nevadascout** [comment]
Another nice find, I'll sort that out too.

I plan to use Crane to develop with for most of the day tomorrow, so hopefully I'll be able to find any other similar issues.

**Comment by nevadascout** [comment]
Right, @TheColorRed - can you give this a go now?

I've rewritten the suggestion engine and tested it on a fairly large project without noticing any issues my end.

**Comment by TheColorRed** [comment]
Not sure if I am doing something wrong, but I am not getting any suggestions...

1. Updated local repo with `feature/signatureHelp`
1. Updated npm (both server/client) `sudo npm install`
1. Built the server `Ctrl+Shift+B`
1. Ran the client `F5`

Here are my results.

No class suggestion:

screenshot from 2016-06-19 11-40-17

No method-only suggestion (The method is in there but it was from vscode not crane):

screenshot from 2016-06-19 11-46-05

**Comment by nevadascout** [comment]
Did you rebuild the source cache? (I doubt that's it, but worth trying?)

**Comment by TheColorRed** [comment]
I deleted the whole `Crane/project` folder, started it up, and let it rebuild the whole project from scratch.

**Comment by nevadascout** [comment]
Hmm, that's very odd. Let me try recreating my repository locally to reproduce this

**Comment by nevadascout** [comment]
Can you try pulling the latest version of the branch and trying again? It much be a weird npm caching issue or something

**Comment by TheColorRed** [comment]
I'm Still getting the same thing...

**Comment by nevadascout** [comment]
Strange, it works on both Windows and OSX for me.

There isn't a parse error anywhere in your code is there? That can prevent the parser from building the AST needed to create the suggestions

**Comment by TheColorRed** [comment]
Code doesn't show that there are any errors. 

Here is my console output:

```
Loading development extension at /home/ryan/Documents/GitHub/crane/client
linux
Crane Initialised...
vscode-icons is active!
Spell and Grammar checker active...
```

Then here is my Cran Console (offtopic: There is a typo `Cache file successfullly read` with one too many `l`'s):

```
[INFO] Building project from cache file: /home/ryan/Crane/projects/ec32c125403e54c19820b88b0f0f56f9/tree.cache
[INFO] Unzipping the file
[INFO] Cache file successfullly read
[INFO] Loaded
[INFO] Processing complete!
[INFO] packing tree file: /home/ryan/Crane/projects/ec32c125403e54c19820b88b0f0f56f9/tree.cache
[INFO] Cache file updated
[INFO] Processing complete!
```

**Comment by nevadascout** [comment]
Do you have Skype or another IM service I could talk to you on to try to help more?

**Comment by TheColorRed** [comment]
I have a Google Hangouts account, and a Facebook account. I would have to check if I have a Skype.

**Comment by TheColorRed** [comment]
Found my Skype ID. "ryan.naddy"

**Comment by nevadascout** [comment]
I think I've added you on Skype.. There were several with the same name

**Comment by TheColorRed** [comment]
I didn't get any request

**Pull request merged**
