### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by TheColorRed**
Moved changes to CHANGELOG.md

### CODE REVIEW

**Comment by nevadascout** [comment]
As I said on the other PR, I want to keep the changelog in the readme file as well so they are visible on the project homepage, as well as the vs marketplace page.

**Comment by TheColorRed** [comment]
Okay, I created this pull before reading your message.

The changelog.md should show up on both the market place: https://marketplace.visualstudio.com/items?itemName=HvyIndustries.crane/changelog

and in the editor under the `changelog` tab in the extension.

**Comment by nevadascout** [comment]
No worries!

That link you put doesn't work btw 😄

**Comment by TheColorRed** [comment]
Yeah,  it doesn't work because the changelog hasn't been uploaded ;)

**Comment by nevadascout** [comment]
Just noticed the problem - the `changelog.md` file needs to go in the `client/` directory. I've now moved it and republished to the marketplace

**Pull request closed without merging**
