### PR TITLE
Update Cranefs.ts

### PR DESCRIPTION
**Pull request by VxMxPx**
Adds linux configuration directory, to avid littering home.
Fore details see: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

### CODE REVIEW

**Comment by nevadascout** [comment]
Hey, thanks for this code! I'm not able to test this right now, so maybe you can answer this question:

Have you tested if this creates the `.config` folder if it doesn't exist?

**Comment by VxMxPx** [comment]
The config should exists in most cases. I cannot have functional desktop environment without .config. I can give it a try tomorrow though, replacing .config with something else.

(The question here is only if directories are being created recursively, so .config, then Crane if neither of them exists).

**Comment by nevadascout** [comment]
I'm pretty sure we create the `crane` directory, so it would make sense for the `.config` directory to be created as well, but I'm not 100% sure...

Thanks for checking :)

**Comment by TheColorRed** [comment]
The Crane directory is getting created using `mkdirp`, which recursively creates any directories which do not exist. 

Library: https://www.npmjs.com/package/mkdirp

**Pull request merged**
